config:
  http:
    timeout: 30
  phases:
    - duration: 300
      arrivalRate: 1
      name: Generating tenant load
  # Add environment variables for API key
  variables:
    apiKey: "{{ $processEnvironment.API_KEY }}"

scenarios:
  - name: Start Execution
    flow:
      - post:
          url: "/generateLoad"
          headers:
            Content-Type: "application/json"
            x-api-key: "{{ apiKey }}"
          json:
            groups:
              - MessageGroupId: "group-1"
                count: 500
              - MessageGroupId: "group-2"
                count: 25
              - MessageGroupId: "group-3"
                count: 25
              - MessageGroupId: "group-4"
                count: 25
              - MessageGroupId: "group-5"
                count: 25
              - MessageGroupId: "group-6"
                count: 25
              - MessageGroupId: "group-7"
                count: 25
              - MessageGroupId: "group-8"
                count: 25
              - MessageGroupId: "group-9"
                count: 25
              - MessageGroupId: "group-10"
                count: 25
